import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
    price: 299.99,
    originalPrice: 399.99,
    image: "/premium-wireless-headphones.png",
    category: "Electronics",
    rating: 5,
    reviews: 128,
    badge: "Best Seller",
    inStock: true,
    features: ["Noise Cancellation", "30hr Battery", "Premium Sound"],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Advanced fitness tracking with heart rate monitoring and GPS functionality.",
    price: 249.99,
    image: "/smart-fitness-watch.png",
    category: "Electronics",
    rating: 4,
    reviews: 89,
    badge: "New",
    inStock: true,
    features: ["Heart Rate Monitor", "GPS", "Water Resistant"],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt in various colors.",
    price: 29.99,
    image: "/organic-cotton-t-shirt.png",
    category: "Clothing",
    rating: 4,
    reviews: 156,
    inStock: true,
    features: ["Organic Cotton", "Sustainable", "Comfortable Fit"],
  },
  {
    id: "4",
    name: "Professional Camera Lens",
    description: "High-performance camera lens for professional photography and videography.",
    price: 899.99,
    image: "/professional-camera-lens.png",
    category: "Electronics",
    rating: 5,
    reviews: 67,
    inStock: false,
    features: ["Professional Grade", "Sharp Images", "Durable Build"],
  },
  {
    id: "5",
    name: "Ergonomic Office Chair",
    description: "Comfortable ergonomic office chair with lumbar support and adjustable height.",
    price: 399.99,
    originalPrice: 499.99,
    image: "/ergonomic-office-chair.png",
    category: "Furniture",
    rating: 4,
    reviews: 203,
    inStock: true,
    features: ["Lumbar Support", "Adjustable Height", "Breathable Mesh"],
  },
  {
    id: "6",
    name: "Stainless Steel Water Bottle",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours.",
    price: 34.99,
    image: "/stainless-steel-bottle.png",
    category: "Lifestyle",
    rating: 5,
    reviews: 312,
    badge: "Eco-Friendly",
    inStock: true,
    features: ["24hr Cold", "BPA Free", "Leak Proof"],
  },
  {
    id: "7",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
    price: 49.99,
    image: "/wireless-charging-pad.png",
    category: "Electronics",
    rating: 4,
    reviews: 94,
    inStock: true,
    features: ["Fast Charging", "Qi Compatible", "LED Indicator"],
  },
  {
    id: "8",
    name: "Premium Coffee Beans",
    description: "Single-origin premium coffee beans roasted to perfection for the ultimate coffee experience.",
    price: 24.99,
    image: "/placeholder-6b2pz.png",
    category: "Food & Beverage",
    rating: 5,
    reviews: 178,
    badge: "Artisan",
    inStock: true,
    features: ["Single Origin", "Fresh Roasted", "Premium Quality"],
  },
  {
    id: "9",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with rich sound and long battery life.",
    price: 79.99,
    image: "/bluetooth-speaker.png",
    category: "Electronics",
    rating: 4,
    reviews: 145,
    inStock: true,
    features: ["Portable", "12hr Battery", "Waterproof"],
  },
  {
    id: "10",
    name: "Yoga Mat",
    description: "Non-slip yoga mat made from eco-friendly materials for comfortable practice.",
    price: 39.99,
    image: "/rolled-yoga-mat.png",
    category: "Fitness",
    rating: 4,
    reviews: 89,
    badge: "Eco-Friendly",
    inStock: true,
    features: ["Non-slip", "Eco-friendly", "6mm Thick"],
  },
]
